name: Build & Push Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: propentatech/portfolios-formation-web2026

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

      - name: Trigger Dokploy Deploy
        run: |
          curl -X GET "${{ secrets.WEBHOOK_URL }}"
